pakcage api

	
type AutoGenerated struct {
	Copyright string `json:"copyright"`
	Roster    []struct {
		Person struct {
			ID       int    `json:"id"`
			FullName string `json:"fullName"`
			Link     string `json:"link"`
		} `json:"person"`
		JerseyNumber string `json:"jerseyNumber"`
		Position     struct {
			Code         string `json:"code"`
			Name         string `json:"name"`
			Type         string `json:"type"`
			Abbreviation string `json:"abbreviation"`
		} `json:"position"`
	} `json:"roster"`
	Link string `json:"link"`
}